### ISSUE TITLE
System is still `Read-only` after `adb remount`

### ISSUE THREAD

**Issue by imknown** [0xFireball/root_avd#2]
I found [this](https://www.pocketmagic.net/write-on-the-android-read-only-file-system/), and it worked... Tested on `Android-P Google API x86 avd`.
``` bash
adb shell mount -o rw,remount -t rootfs /
```

**Comment by 0xFireball** [comment]
This guide was originally made for Nougat; thanks for the update, things may have changed.

**Comment by A-AFTAHI** [comment]
it didn't work for me i'm stuck on the remount part any help. @imknown  i tried what you suggested but didn't work neither

**Comment by imknown** [comment]
@A-AFTAHI This issue "System is still `Read-only` after `adb remount`" disappears now.
Try to use what `README.md` said.

(Xubuntu 18.10 AMD64 + Android-9 Google API x86 avd)

``` sh
./emulator -avd 'Android-9' -writable-system -selinux permissive -qemu -enable-kvm
# emulator: WARNING: System image is writable
# qemu_ram_alloc_user_backed: call
# emulator: INFO: boot completed
# emulator: INFO: boot time 17820 ms
```

``` sh
adb root                                                                          
# restarting adbd as root

adb remount
# remount succeeded

adb push '/home/imknown/Desktop/imknown' /system
# /home/imknown/Desktop/imknown: 1 file pushed.
```
